version: '2.2'
services:
  postgres:
    image: postgres:${VERSION}
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "autovacuum_freeze_max_age=2000000"
      - "-c"
      - "log_autovacuum_min_duration=0"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    volumes:
      - ./:/data
